### ISSUE TITLE
JSON file in local directory

### ISSUE THREAD

**Issue by nelsaow** [SheldonWangRJT/JSON-Downloading-Demo#1]
If I put the JSON file in local directory, like inside the project the project, How should I do? I couldn't figure out it, Can you help me? Thanks

**Comment by SheldonWangRJT** [comment]
I have a video tutorial of reading .txt .json .plist files. You can check that tutorial.
The Youtube link is: https://www.youtube.com/watch?v=PWgRz4jqICI
The finished project link in Github is: https://github.com/SheldonWangRJT/Read-Write-txt-json-plist.git
